$ANSIBLE_VAULT;1.1;AES256
64633337646132393764336566616137656136363466386138373337663231303065303962366437
6462643465366662633732636161303130393038373039330a643661376139643663656264663933
36383234396135623934313033343032656264616563363763656535303666376662313132366131
6236333939633033630a343431633430353834376261396338306639386137613863343630383436
65646666306432366632653263386432343831333866316237353064333862613133393738343564
31656332666238613638386539393632383963613037633664383765643736316234623131663266
36366461366138656238303734613561613162633039393432343761333038303833336436663031
30306138666234323466616433333035366436633538653336343734613432303337353938643165
35663535636130373736393230376231383262363961323733613761383530613739646461633539
66316137383039373231316539383739356135313834316465353963313530643833653930353865
376432626234383261653334623864343366
